import { relative, basename, extname } from 'path';
import { promises as fs } from 'fs';

/**
 * @param {object} [options]
 * @param {object} [options.inline = false] Emit a Data URL module exporting the URL string.
 * @param {object} [options.cwd] Used to resolve the URL when `inline` is `true`.
 * @returns {import('rollup').Plugin}
 */
export default function urlPlugin({ inline, cwd } = {}) {
	const isImplicitUrl = id => !/\.(?:js|cjs|mjs|jsx|ts|tsx|css|s[ac]ss|map|html|json)$/i.test(id) && !!extname(id);
	const escapeUrl = url => url.replace(/#/g, '%23').replace(/'/g, "\\'").replace(/"/g, '\\"');

	return {
		name: 'url-plugin',
		async resolveId(id, importer) {
			if (id[0] === '\0') return;

			if (id.startsWith('url:')) {
				// explicit `url:` prefix
				id = id.slice(4);
			} else if (!inline) {
				// In dev mode, we eagerly process un-prefixed non-source files.
				// This would be an infinite Rollup loop for prod, which instead uses load().
				return;
			} else if (!isImplicitUrl(id)) {
				// implicitly apply `url:` all files except source code
				return;
			}

			const resolved = await this.resolve(id, importer, { skipSelf: true });
			if (!resolved) return;

			// In dev mode, we turn the import into an inline module that avoids a network request:
			if (inline) {
				const url = '/' + relative(cwd, resolved.id).replace(/^\./, '') + '?asset';
				return {
					id: escapeUrl(`data:text/javascript,export default${JSON.stringify(url)}`),
					external: true
				};
			}
			resolved.id = `\0url:${resolved.id}`;
			return resolved;
		},
		async load(id) {
			if (id.startsWith('\0url:')) {
				// explicit `url:` prefix (generated by our resolveId):
				id = id.slice(5);
			} else if (!isImplicitUrl(id)) {
				// implicitly apply `url:` all files except source code
				return;
			}

			const fileId = this.emitFile({
				type: 'asset',
				name: basename(id),
				source: await fs.readFile(id)
			});
			this.addWatchFile(id);
			return `export default import.meta.ROLLUP_FILE_URL_${fileId}`;
		}
	};
}
